name: ci-fc3.0-go
on:
  pull_request:
    branches:
      - dev
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.23.5
      - run: go mod download
      - run: go test -v ./...
      - run: go run main.go
